""" MySQL vs. SQL Webpage Notes
    -> outline
        -> introduction
        -> MySQL vs SQL
        -> what is SQL
            -> what SQL is used for
        -> what is MySQL
            -> what is a relational database
            -> is MySQL free?
            -> what kind of server is MySL
            -> MySQL advantages
        -> summary <- SQL vs MySQL
    -> introduction
        -> MySQL vs SQL
    -> MySQL vs SQL
        -> SQL IS A QUERYING LANGUAGE FOR RELATIONAL DATABASES
        -> MYSQL IS A DATABASE SOFTWARE APPLICATION
            -> AN RDBSM <- RELATIONAL DATABASE MANAGEMENT SYSTEM
        -> SQL is the language you use to interact with the database, MySQL is the database that stores it
    -> what is SQL
        -> SQL is a computer language, for database management and manipulation
        -> STRUCTURED QUERY LANGUAGE
            -> it is also pronounced sequel, or just SQL (letters)
        -> this has been an international standard, since 1987
        -> THE SQL STANDARD IS THE CURRENT VERSION OF THE SQL INTERNATIONAL STANDARD AT A GIVEN POINT IN TIME
    -> what is SQL used for
        -> RDBMS's <- RELATIONAL DATABASE MANAGEMENT SYSTEMS, USED TO MANAGE RELATIONAL DATABASES
            -> e.g, MySQL, support SQL
            -> Select, Delete, Update, Create and Drop SQL commands interact with these
            -> context
                -> it can be embedded in the code
                -> embedded into code in another language
                -> written directly into the database
                -> it can also be used with a language-specific API that can hide SQL syntax
    -> what is MySQL
        -> MySQL is an RDBMS
        -> benefits
            -> reliable
            -> easy to use
            -> high-performing
            -> handling data in an organised way
        -> SQL is the language it uses, to query the database
        -> other RDBMS examples
            -> PostgreSQL
            -> Oracle
            -> Microsoft SQL Server
            -> MongoDB
            -> once you know one of them, you can use the rest
                -> each RDBMS is more similar than different
        -> what is a relational database
            -> RDBMS  <- a system for storing and providing access to related data points
            ->  THEY ORGANISE DATA INTO SCHEMAS
                -> TABLES WITH ROWS AND COLUMNS, WHICH ARE CONNECTED BY PRE-DEFINED RELATIONSHIPS
                -> statistics
            -> optimised for speed
            -> the relational database rules are to ensure speed and avoid inconsistent, duplicate, out-of-date or
                missing date
            -> THEY USE SQL
            -> MYSQL IS A RELATIONAL DATABASE MANAGEMENT SYSTEM (RDBMS)
        -> is MySQL free?
            -> it is an open source software / RDBMS
            -> it is free
            -> there is source code that you can study
                -> you can change the code for your context
            -> IT USES GNU <- GENERAL PUBLIC LICENSE
                -> to define what you can nd can't do wit the software
                -> you can use their code in a commercial application
                    -> you would have to buy a commercial license from Oracle for this
        -> what kind of server is MySQL
            -> IT USES A MULTITHREADED SQL SERVER, THAT OPERATES AS A CLIENT / SERVER SYSTEM
            -> this supports different backends, client programs and libraries, administrative tools
            -> API <- APPLICATION PROGRAMMING INTERFACE
            -> it has an embedded multithreaded library <- the application can become smaller, faster and easier to
                manage
        -> MySQL advantages
            -> it is for handling large databases
            -> it has been used for decades
            -> it offers sets of functions and is under development constantly
            -> connectivity, speed and security
            -> for accessing databases on the internet
            -> it is commonly used by applications we use
            -> IT OPERATES ON THE DESKTOP / LAPTOP WITH OTHER APPLICATIONS AND SERVERS
            -> you can allocate an entire machine to MySQL
                -> this would allow you to fine-tune the settings to optimise the memory avaliale, CPU power and I/O
                    capacity
                -> it is scalable and can extend to other interconnected machines
            -> advantages
                -> fast
                -> reliable
                -> SCALABLE
                -> easy to use
                -> widely used and supported
            -> summary
                -> SQL IS A QUERYING LANGUAGE
                    -> for managing, manipulating and querying RELATIONAL DATABASES
                -> MySQL IS A SOFTWARE APPLICATION FOR EDITING RELATIONAL DATABASES <- RELATIONAL DATABASE MANAGEMENT
                    SYSTEM: RDBMS
                    -> THEY STORE DATA IN SEPARATE TABLES THAT ARE CONNECTED BY RELATIONSHIPS BETWEEN THEIR COLUMNS
                -> MySQL is free open source software
                    -> anyone can use it / modify it
"""