""" Video: What is a Database? Video Notes
    -> outline
        -> what is a database
        -> database types
        -> the most popular databases
        -> what is SQL
        -> what is MySQL
        -> MySQL vs SQL
        -> how to use MySQL Workbench
    -> talking about databases at a big picture
        -> keywords
        -> relational and non-relational
            -> relational databases <- MySQL
            -> oracle, IBM, SQLServer
            -> different companies have them for managing users, inventory, etc
            -> tech companies use relational databases
        -> using IoT
            -> millions of records per days
                -> the queries in relational models can take too long
                -> the models might also not fit the data
                -> this is why we use NoSQL databases
                    -> Splunk, CouchDB, Cassandra
                    -> they are for a different use case
                        -> more data
        -> MySQL
            -> SQL is a language <- Structured Query Language, for querying the data
            -> MySQL is a software application, for managing the data
            -> different companies have relational databases at their core
            -> this is a database technology
        -> MySQL Workbench
            -> this has a GUI and is for interacting with MySQL
            -> it has a GUI
            -> for working with MySQL databases
            -> for vosualising how databases are related to each other
        -> MySQL
            -> he logs into the shell in the terminal
            -> use sakila <- this is an example of an SQL command that can be used with it
            -> he is selecting different tables with it
                -> different syntax for querying the databases
                -> DIFFERENT DATABASES HAVE DIFFERENT CONNECTIONS / SCHEMAS
                    -> relational
            -> using it for the sakila database
                -> this is what he types into the RDBMS
                -> for working with entity relationshp diagrams
                -> how the tables are related to each other
                    -> relational
        -> differences
            -> SQL <- Structured Query Language, for querying databases
            -> MySQL <- an application for managing databases (RDBMS, Relational Database Management System)
                -> this is done with SQL
            -> MySQLWorkbench
                -> a GUI for interfacing with MySQL databases
        -> relational
            -> they are similar to Excel spreadsheets, except the spreadsheets are linked more closley with each other
                -> you can also process them analytically
            -> cubes of data
            -> YOU CAN CREATE PIVOT TABLES
            -> vertical
            -> comments
            -> fast databases
                -> working down the columns, without relations between them
            -> A HASHMAP IS A KEY-VALUE STORE
            -> we have specific tools for specific jobs
                -> different companies use different RDBMS's
                -> databasing / interfacing applications
        -> Facebook has one called Cassandra
            -> more complex than relational
        -> types
            -> 
"""