""" Installing and Connecting to MySQL Workbench Webpage Notes
    -> outline
        -> introduction
        -> what is MySQL Workbench
        -> how to install MySQL Workbench
        -> how to create a MySQL database connection
        -> Summary: how to install MySQL Workbench and create a MySQL database connection
    -> what is MySQL Workbench
        -> MySQL WORKBENCH IS A GUI FOR INTERACTING WITH MySQL
        -> MySQL IS AN APPLICATION FOR RELATIONAL DATABASE MANAGEMENT
            -> THIS IS RUN IN THE CLI
        -> MySQL WORKBENCH INTRODUCES A GUI FOR THIS
    -> how to install MySQL Workbench
        -> follow the instructions on their website
        -> this is at https://dev.mysql.com/doc/workbench/en/wb-installing-windows.html
    -> How to create a MySQL database connection
        -> creating a new MySQL database connection, from inside MySQL
        -> launch the application and click the + icon, to create a new connection
        -> configure the settings for this connection
        -> click Store in Keychain
        -> type the MySQL password that we saved when installing MySQL
        -> click OK
        -> click Test connection
        -> make sure it is running, or the test will fail
        -> if the test succeeds, it will look like the screenshot on the course webpage, at https://codingnomads.com/how-to-install-mysql-workbench
        -> if you see a screen with an error, then you need to start the MySQL server
            -> then you quit MySQL Workbench, start MySQL and relaunch MySQL Workbench
    -> Summary: how to install MySQL Workbench and create a MySQL database connection
        -> you can install MySQL Workbench by following the official instructions on their webpage
        -> you then create a MySQL database connection using the local host default data
"""