""" Using MySQL Workbench Video Notes
    -> outline
        -> using MySQL Workbrench
        -> we are using the Sakila DB database
        -> we don't have to have the Sakila database installed before watching the video
            -> he does examples on this database in this video
        -> we install the database in upcoming sessions (not this one)
    -> SQL is for querying the database
    -> MySQL is an application for RDBMS (Relational Database Management System)
        -> this runs in the terminal
        -> MySQL Workbench is the same thing, but with a GUI
        -> we previously installed this
        -> this required making a connection to a local host
    -> in MySQL Workbench
        -> it has a GUI
            -> this is a GUI for MySQL databases
            -> IT CONNECTS TO DIFFERENT DATABASES, THESE ARE CALLED CONNECTIONS
        -> it manages multiple connections to multiple databases
        -> we want to connect to the local host
            -> MySQL has to be running on the machine for this to work
            -> there are instructions for this in the course webpages
        -> on the LHS, it shows the different databases that he is connected to
            -> the Sakila database is an open-source database for movie rentals
                -> this can be opened by double clicking on it
                -> Sakila is the default database
        -> you can run an SQL command in the main pane
            -> you can set a default database for this
            -> you can right click on the table and click select rows
            -> you can right click and alter the table as well
                -> this lets you change the table attributes
                -> BIN <- binary
                -> PK <- primary key
                -> NN <- not null
                -> UQ <- unique
                -> UN <- UNSIGNED (NO SIGN)
                    -> ONLY POSITIVE NUMBERS
                -> ZF
                -> AI <- auto increment
                -> G <- generated columns
                    -> a value that MySQL will generate, for example when you insert a record
                    -> there are multiple ways you can generate a field
                    -> do an update to the current timestamp, for example
                        -> timestamps are automatically generated when you update the table
                -> to alter table, change the column or the datatype
                -> he goes to the actor table, you can click on the icon that looks like a spreadsheet with a lightning
                    bolt on the LHS, to select the top 200 database entries
                -> you can also click the refresh button
                    -> this is used, for example if there are changes to the database schema
                -> if you want to change the last name of a woman in the database
                    -> you can change the name of an actor in the database, by clicking on it and typing the entry
                    -> you can get a representation of all the tables
                    -> he changes one of the names
                    -> this changes the name in the database
                        -> he then applies tihs change
                        -> he uses the GUI
                            -> doing this is equivalent to typing SQL commands, which it then shows
                -> WORKING WITH ENTITY RELATIONSHIP DIAGRAMS
                    -> there is a tabl that is open with a new database connection
                    -> there is a file called skila.mwb for this
                        -> he opens this file in MySQL Workbench
                        -> you can use this to visualise the database
                        -> IT SHOWS THE CONNECTIONS BETWEEN THE DATABASE SCHEMAS
                        -> THIS IS AN .mwb FILE
                        -> you can also create a table structure
                            -> see the column names, the data types, attributes and more
                -> MySQL Workbench has an  
"""