""" What is a Relational Database? Webpage Notes 
    -> outline
        -> introduction
        -> what is a relational database?
            -> relational databases design
            -> relational schemas
            -> relational database tables
        -> example of a relational database
        -> summary: what is a relational database?
    -> introduction
        -> Dr E. F. Codd
            -> IBM researcher
            -> published a paper in 1970
            -> HE PROPOSED RULES FOR ORGANISING AND MANIPULATING DATA IN A RELATIONAL DATABASE
                -> these
    -> what is a relational database?
    -> relational databases design
    -> relational schemas
    -> relational database tables
    -> example of relational database
    -> summary: what is a relational database?
"""