""" What is a Relational Database? Webpage Notes 
    -> outline
        -> introduction
        -> what is a relational database?
            -> relational databases design
            -> relational schemas
            -> relational database tables
        -> example of a relational database
        -> summary: what is a relational database?
    -> introduction
        -> Dr E. F. Codd
            -> IBM researcher
            -> published a paper in 1970
            -> HE PROPOSED RULES FOR ORGANISING AND MANIPULATING DATA IN A RELATIONAL DATABASE
                -> THESE ARE CALLED THE CODD RULES <- PRINCIPLES OF RELATIONAL DATABASES
                -> tables, rows and columns
                -> THIS PAPER DEFINES THE USE OF SQL
                    -> for accessing and manipulating the data
                    -> SQL <- STRUCTURED QUERY LANGUAGE SQL
            -> the firs commercial RDBMS's were then introduced in the 1980s
                -> IBM's System R
                -> Oracle's databases
                -> these were based on Codd's ideas
                    -> they are a foundation for the RDBMS's used today
    -> what is a relational database?
        -> RDBMS <- RELATIONAL DATABASE MANAGEMENT SYSTEM
            -> FOR MANAGING RELATED DATAPOINTS
                -> accessing and manipulating them
        -> RELATIONAL MODELS <- TO ORGANISE DATA INTO A SPREADSHEET FORMAT
        -> these use SQL to manage and query the database data
    -> relational databases design
        -> RELATIONAL DATABASES USE SCHEMAS
            -> THESE DOCUMENT THE RELATIONSHIPS BETWEEN TABLES OF DATA
            -> DATA FIELDS <- COLUMNS
                -> MANY-MANY, ONE-TO-ONE, ONE-TO-MANY, UNIQUE, REQUIRED OR OPTIONAL
                -> pointers between different tables
                -> the database enforces these relationship rules
                    -> this means the application avoids inconsistent, duplicate, orphan, out-of-date, or missing data
        -> they can be organised into physical files, that are optimised for speed
            -> logical organisation <- for a flexible programming environment
                -> this uses objects such as databases, tables, views, rows, and columns
                -> DATABASES CAN INCLUDE MANY TABLES, NOT THE OTHER WAY AROUND
                -> they have a lesson on database schemas, that details this
    -> relational schemas
        -> A RELATIONAL SCHEMA IS A BLUEPRINT OF HOW ALL DATABASE ITEMS ARE RELATED TO EACH OTHER
        -> THEY ARE REPRESENTED AS A DIAGRAM OF CONNECTED TABLES, FOR EXAMPLE BY MySQLWorkbench
    -> relational database tables
        -> RELATIONAL DATABASE TABLES are tables that the RDBMS holds
        -> they look like a spreadsheet
            -> columns hold one kind of data
            -> A FIELD IS LIKE A CELL IN THE SPREADSHEET <- IT STORES THE INFORMATION (ATTRIBUTE)
            -> each row represents a series of related values
                -> EACH ROW CAN BE MARKED WITH A PRIMARY KEY <- THIS IS A UNIQUE IDENTIFIER
            -> ROWS AMONG MULTIPLE TABLES CAN BE RELATED, BY USING FOREIGN KEYS
        -> the data in these tables can be accessed many different ways
            -> MySQL in the terminal
            -> the MySQLWorkbench application <- nicer GUI, but application required
            -> this can be done, without having to reorganise the database tables themselves
        -> the Amazon website has more information about this
    -> example of relational database
        -> THERE IS A DIAGRAM OF THE SCHEMAS IN A RELATIONAL DATABASE
            -> THIS IS THE KIND OF TABLE THAT MYSQL WORKBENCH CAN GENERATE
            -> this only contains information about one particular element
            -> e.g, the Passenger table only contains information related to the Passenger
                -> the Flight table only contains information about the flight
                -> INFORMATION RELEVANT TO EACH TABLE IS ONLY CONFINED TO THAT TABLE
                -> TABLES CAN BE RELATED USING KEYS
                    -> this is later in the course
                -> THIS IS THE RELATIONAL SCHEMA DESIGN -> RELATING DATABASE TABLES TO EACH OTHER, BY USING KEYS
                -> this keeps the data
                    -> clean
                    -> concise
                    -> scalable
    -> summary: what is a relational database?
        -> RDBMS <- RELATIONAL DATABASE MANAGEMENT SYSTEM
        -> 
"""