""" Tutorial on Relational Database Design Webpage Notes 
    -> outline
        -> introduction
        -> database design objective
        -> relational database design process
            -> step 1: define the purpose of the database
            -> step 2: gather data, organise in tables and specify the primary keys
            -> step 3: create relationships among tables
                -> one-to-many
                -> many-to-many
                -> one-to-one
            -> step 4: refine and normalise the design
                -> normalisation
                -> first normal form
                -> second normal form
                -> third normal form
                -> higher normal form
                -> integrity rules
                -> column indexing
            -> references and resources
    -> introduction
        -> this is an explanation of why relational databases are considered relational
        -> this is a quick-start tutorial
        -> relational databases were proposed by Edgar Codd
            -> IBM research
            -> 1916
        -> the dominant database model for commercial applications
            -> in comparison to other database models <- hierarchical, network and object models
        -> RDBMS <- Relational Database Management System
            -> Oracle, IBM DB2, Microsoft SQL Server
            -> there are free / open source ones <- MySQL, mSQL (mini SQL), embedded JavaDB (Apache Derby)
        -> RELATIONAL DATABASES ORGANISE DATA IN SPREADSHEETS
            -> TABLES ARE THE RELATIONS
            -> A COLUMN IS CALLED A FIELD, OR ATTRIBUTE
        -> relationships can be created among the tables
            -> this enables the database to store large amounts of data and retrieve selected data
            -> SQL <- STRUCTURED QUERY LANGUAGE
    -> database design objective
        -> we-designed databases will:
            -> eliminate data redundancy
                -> the same piece of data isn't stored in the same place
                -> duplicate data wastes storage space and leads to insecurities
            -> ensure data integrity
            -> ensure the accuracy of data
    -> relational database design process
        -> about
            -> DATABASE DESIGN requires many decisions
                -> IT IS CONTEXT DEPENDENT
                -> for a particular application
                    -> no two are the same
                    -> guidelines, in terms of what not to do, rather than what to do - are provided in making the design
                        decision, but the choices are individual
        -> step 1: define the purpose of the database (requirement analysis)
            -> gather the requirements
            -> define the database objective
            -> this can require drafting input forms / queries, etc
        -> step 2: gather data, organise tables and specify the primary keys
            -> we decide the purpose of the database
            -> then we the data it stores
                -> we want to divide this into tables
                -> WE CHOOSE ONE COLUMN, OR MULTIPLE, AS THE PRIMARY KEY
            -> primary key
                -> IN THE RELATIONAL MODEL, THE TABLE CAN'T CONTAIN DUPLICATE ROWS
                    ->     
"""