""" Create a DB Schema + Tables Webpage Notes 
    -> outline
        -> introduction
        -> how to create a database schema in MySQL
            -> a database schema refers to how the tables in a relational database are connected
                -> e.g, by their columns
        -> how to add a table using MySQL: create table
            -> MySQL is an application for Relational Database Management (RDBMS)
            -> the language it uses to query the database is SQL (Structured Query Language)
            -> MySQL can be run in the CLI, or using an open-source application called MySQL Workbench
                -> this contains a GUI
        -> Summary: create a database schema and table in MySQL
    -> introduction
        -> to create a relational database schema with MySQL, we first need to connect to the RDBMS
            -> relational database management system
            -> we then need to create the tables and relationships between them that are required for the application
            -> IN THIS LESSON, WE ARE CREATING A MYSQL DATABASE AND TABLE
    -> how to create a database schema in MySQL
        -> steps for usingMySQL to create a database schema in Mac, Windows and Linux
        -> install MySQL on the machine
            -> this is checked, by running `mysql --version` from the CLI
            -> if this isn't installed, refer to their instructions on how to install MySQL
        -> run MySQL on the machine
            -> Mac
                -> sudo /usr/local/mysql/support-files/mysql.server start
                -> sudo launchctl load -F /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist
            -> Linux
                -> /etc/init.d/mysqld start
                -> service mysqld start
                -> service mysql start
            -> Windows
                -> C:\>"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqld"
        -> open MySQL Workbench
        -> connect to the "localhost" connection
            -> we need to set up this connection before doing this
            -> this was covered on a previous webpage
        -> in the open query tab, we run this SQL command:
            -> create schema SocialDB;
            -> and then execute it, by clicking the lightning bolt
        -> we then refresh the "schemas" tab on the left side of the screen
            -> this shows the new schema, by clicking the refresh icon
        -> we then expand the SocialDB Schema
            -> this is done by clicking the arrow next to it
    -> we then add a table using MySQL <- we create a table
        -> right click on Tables and Create Table
        -> we then create the Users table, to match the image shown on the course webpage, at https://codingnomads.com/mysql-create-database-schema-mysql-create-table-tutorial
        -> AI <- AUTO-INCREMENT
            -> THIS MEANS THAT THE FOREIGN KEYS OF THE TABLE CAN INCREASE IN ONES, SO THEY ARE NON-REPEATED NUMBERS
            -> the DateCreated field sets the default TimeStamp to the "Current_Timestamp"
        -> we then Apply, to execute the following SQL statement: 
"""