""" Creating a Simple Relational Database Video Notes 
    -> outline
        -> how to create a database using MySQL
        -> using MySQL workbench
        -> creating a schema
        -> creating database tables
        -> inserting new data
        -> applying primary and foreign keys
    -> creating a relational database in MySQL Workbench
    -> make the connection
        -> you can click on the + buttons
        -> 127.0.0.1 <- this is the hostname, the connection is hosted on our computer
        -> the port name is 33016 <- default for MySQL
        -> you can call the connection name whatever you want
        -> DON'T USE THE ROOT USER AS THE USERNAME IN THE REAL WORLD
        -> then store in keychain <- this is the password
        -> then testing the connection and seeing the success message
            -> MySQL has to be running on the machine
            -> it has to be to the correct connection
    -> this creates a new connection
        -> in the local MySQL installation
            -> there is sys and information schema
            -> socialDB <- he drops this database, to recreate it
    -> creating the database
        -> we want to create a database for a social media application
            -> users
            -> images
            -> posts
            -> users' friends
        -> right click > create schema > utf8-default
        -> MySQL Workbench ALLOWS YOU TO REVIEW THE SQL
            -> applying this change
        -> refresh the changes
        -> he expands SocialDB, right clicks and creates the Users table
            -> creating the UserID table
                -> this auto-increments
            -> the next column is for the name of the user
                -> we are setting a limit to the amount of characters
                -> NOT NULL MEANS THAT THE DATA IT CONTAINS HAS TO EXIST
                -> he also makes an email column
            -> then adding a date created column
                -> this contains timestamps
                -> its default value is the current timestamp
                -> when the element is updated, this changes
                -> APPLYING THESE CHANGES IN MYSQL WORKBENCH CREATES SQL, THAT IT SHOWS YOU
                    -> this shows the default values of different elements, the primary key and others
                    -> the auto-incrementing ID is used as the primary key
                    -> WE WANT DATA THAT DOES NOT CHANGE AS THE PRIMARY KEY
        -> we have the database, but there are no users
            -> then, adding three fields
                -> the userID and the date created are auto-created
            -> running this again shows the SQL
                -> this is in a certain order
                -> WE CAN EDIT THE SQL THAT RUNNING MYSQL WORKBENCH GIVES US
                -> then applying these changes
                -> APPLYING THE CHANGES IN MYSQL WORKBENCH EXECUTES THE SQL IT SHOWS YOU
            -> it has inserted a record into the database
    -> creating the users table
        -> 
"""