""" SELECT Webpage Notes 
    -> outline
        -> introduction
        -> key points on SQL syntax
        -> select the database to use
        -> how to use the SQL SELECT statement
        -> SQL select statement examples
            -> 1. Fetch everything
            -> 2. Fetch multiple columns
            -> 3. Fetch one distinct column
        -> summary: SQL Select statement
    -> you don't have to capitalise SQL statements
    -> SQL STATEMENTS HAVE TO END IN A SEMI-COLON
    -> sudo mysql <- TO LOG INTO SQL AS THE ROOT USER
    -> SELECT can retrieve data from one or more tables
    -> SELECT statement syntax:
        -> SELECT <YOUR_COLUMNS> FROM <YOUR_TABLE>;
    -> a JOIN query can be used to select data from one or more tables
    -> example SQL commands
        -> select * from actor; <- everything from the actors table
        -> SELECT first_name, last_name FROM actor; <- just actor first and last names
        -> SELECT actor_id FROM actor; <- one column
"""