""" SELECT WHERE Webpage Notes 
    -> outline
        -> introduction
        -> what does the SQL SELECT WHERE statement do?
        -> how to use WHERE in SQL
            -> Example 1: SQL SELECT WHERE first name
            -> Example 2: SELECT WHERE ID
            -> Example 3: SELECT WHERE length
        -> Summary: the SQL WHERE statement
    -> selecting rows conditionally
    -> it filters selected data
    -> SELECT * FROM sakila.actor WHERE first_name = "JULIA"; <- to select actors with a çertain first name
    -> SELECT * FROM sakila.actor WHERE actor_id = 123; <- to select an actor with a certain ID
        -> this can be done in the terminal (SQL), or in the MySQL Workbench application with a GUI
    -> SELECT * FROM sakila.film WHERE length > 184; <- to select records WHERE a certain condition is True
    -> summary
        -> how to use the SQL WHERE statement
        -> THIS CAN BE USED TO FILTER ROWS WITH A CERTAIN BOOLEAN CONDITION
        -> SQL WHERE syntax
            ->  
"""