""" ORDER BY Webpage Notes 
    -> outline
        -> introduction
        -> how does SQL ORDER BY work?
        -> SQL ORDER BY examples
            -> 1. SQL ORDER BY ascending
            -> 2. SQL ORDER BY descending
            -> 3. SQL ORDER BY field
        -> Summary: SQL ORDER BY
    -> ORDER BY
        -> this is a utility keyword
        -> elements
            -> the SELECT statement can be followed with ORDER BY
            -> one or multiple columns can be ordered
            -> we can choose the order type we want
        -> examples
            -> order by ascending
                -> SELECT * from actor
                    -> selecting all actors
                -> ORDER BY first_name ASC;
                    -> ordering †hem by first name in ascending order
                -> we can use DESC for descending
            -> order by descending
                -> 
            -> order by field
        -> summary
"""