""" INSERT Webpage Notes 
    -> outline
        -> introduction
        -> examples of SQL INSERT INTO
            -> 1. insert two values in two columns
            -> 2. insert one value into one column
        -> summary: the INSERT INTO command
    -> to insert data into the database
    -> examples
        -> 1. insert two values in two columns
            -> INSERT INTO sakila.actor (first_name, last_name)
                -> we are inserting data into the first and last name columns
            -> VALUES ("Coding", "Nomads");
                -> A SECOND LINE CONTAINS THE DATA WE WANT TO ADD INTO THE TABLES
                -> this then shows a success message
            -> SQL auto-generates actor_id and last_update
            -> AI <- THE ID IS AUTO-INCREMENTED
            -> the last_update field has a Default / Expression assigned to CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                -> ALL NEW RECORDS WILL HAVE THE CURRENT TIMESTAMP AUTOMATICALLY INSERTED, AS WELL AS ON UPDATE
                -> when the record is updated, so will the timestamp be
        -> 2. insert one value into one column
            -> we are doing an example for the categories table
            -> this has three fields
                -> two of these are autogenerated
            INSERT INTO sakila.category
              (name)
            VALUES
              ("Cartoon");    --value to insert into it
                -> insert into the sakila category table
                -> these data (Cartoon)
            -> we have to INSERT one non autogenerated field
            -> select * from category where name = "Cartoon";
                -> using a select table, to see what we just inserted
    -> summary
        -> THE INSERT COMMAND INSERTS DATA INTO THE DATABASE TABLE
        -> INSERT COMMAND SYNTAX:
            INSERT INTO <YOUR_TABLE>
              (<YOUR_COLUMNS>)
            VALUES
              (<YOUR_VALUES>);
              -> insert out data in between <>
              -> 

"""