""" CREATE TABLE SELECT Webpage Notes 
    -> outline
        -> introduction
        -> how to create a table in SQL
        -> examples of the CREATE TABLE SELECT statement
            -> 1. CREATE TABLE, SELECT ALL
            -> 2. CREATE TABLE, select specific columns
        -> summary: the SQL CREATE TABLE query
    -> CREATE TABLE <- TO CREATE A TABLE, BASED ON THE RESULTS OF A SELECT QUERY
    -> this defines the order of the command
    -> we CREATE TABLE and choose its name, then selecting what you would like in another table
    -> examples
        -> 1. CREATE TABLE, SELECT ALL
            -> using the `film` and `actor` table in the sakila database
            -> CREATE TABLE actor_backup SELECT * FROM actor;
                -> MAKING A BACKUP OF THE ACTOR TABLE
                -> creating a ctable called actor_backup
                -> selecting everything from the actors table
                -> we are selecting everything from the actors table and creating another table from this 
        -> 2. CREATE TABLE, SELECT SPECIFIC COLUMNS
    -> summary
"""