""" What_is_a_Database? Webpage Notes
    -> outline
        -> introduction
        -> what is a database?
        -> what can you do with a database?
        -> uses for databases
        -> databases vs spreadsheets
        -> database components
        -> different types of databases
        -> the most popular databases list
            -> MySQL
            -> PostgreSQL
            -> Oracle
            -> Microsoft SQL Server
            -> MongoDB
            -> IBM DB2
            -> Redis
            -> Apache Cassandra
        -> summary: what is a database
    -> introduction
        -> DATABASES ARE FOR THE CONTENTS OF WEBPAGES
            -> they contain values
            -> applications rely on databases to store and manage the data
        -> this lesson is about
            -> the definition of a database
            -> common uses for databases
            -> types of databases
            -> the most popular databases <- MongoDB is part of this
    -> definition of a database
        -> a system for organising structured information (data)
            -> rows / columns, like a spreadsheet
            -> this can be done electronically
                -> we can search / store / analyse and modify data, using a computer system
    -> what you can do with a database
        -> managing data <- large amounts of data in a structured system
        -> accurately store data, for it's integrity
        -> safely store data long-term
            -> data only stored by the application could be lost if it shuts down
            -> third-party storage
        -> ACCESSING DATA CONCURRENTLY <- MULTIPLE USERS CAN ACCESS THE SAME DATA
            -> we can manage multiple users and have the data be consistent
        -> retrieving data <- finding data quickly and efficiently
        -> connecting data <- we can connect different pieces of related data together
    -> uses for databases
        -> different industries use databases
        -> online platforms for storing and managing user information
        -> managing customer and sales data
        -> research organisation analysing large amounts of scientific data
        -> government agencies storing millions of records
        -> retail company managing and understanding inventory data
        -> healthcare organisations storing patient information and medical records
    -> databases vs spreadsheets
        -> DATABASES ARE NOT THE SAME AS SPREADSHEETS
        -> database tables are rows and columns
        -> DATABASES ARE MORE POWERFUL AND USEFUL THAN SPREADSHEETS
            -> DATABASES CAN BE QUERIED, SPREADSHEETS CAN'T IN THE SAME CAPACITY
        -> DATA PERSISTENCE <- SAVING DATA TO A DATABASE IN SOFTWARE ENGINEERING
            -> DATA SAVED BY A JAVASCRIPT APPLICATION CAN BE ACCESSED USING A PYTHON ONE
            -> to analyse data
    -> database components
        -> hardware
            -> physical devices that store the database
        -> software
            -> managing / controlling a database
            -> DATABASE MANAGEMENT SYSTEM <- DBMS
        -> data
            -> information stored in the database
        -> DATABASE ACCESS LANGUAGE <- E.G, SQL
            -> the language that allows us to interact with the DBMS (DATABASE MANAGEMENT SYSTEM)
        -> procedures
            -> rules and the DATABASE ARCHITECTURE
            -> the rules determine how we interact with the database information
    -> database types
        -> relational, NoSQL, cloud, centralised, distributed, object-oriented, graph and operational
        -> relational databases
            -> HOW DIFFERENT DATABASES ARE RELATED TO EACH OTHER
            -> these are some of the most common
            -> RELATIONAL DATABASES USE SQL
        -> NoSQL databases
            -> NOT ONLY SQL
            -> NON-RELATIONAL, NON-TABULAR DATABASES
            -> these allow more data storage flexibility
            -> these store and query data in ways that best fit the data
                -> document
                -> key-value
                -> colomnar
                -> graph format
        -> cloud databases
            -> THESE ARE NOT THE ONLY TYPE OF DATABASES
            -> these store information in remote servers
            -> users pay for a subscription
            -> they are used by major companies
    -> most popular databases list
        -> MySQL
            -> about
                -> THIS IS A RELATIONAL DATABASE MANAGEMENT SYSTEM (RDBMS)
                -> this is for storing and managing data
                -> for web applications and data warehousing
                    -> speedy, reliable and relatively easy to use
                -> this uses SQL
                    -> STRUCTURED QUERY LANGUAGE
                    -> this is also used with other languages, e.g PHP, JS and Python
                -> MySQL is one of the most popular RDBMS's
                    -> this is included in this course tutorial series
            -> why use this
                -> high performance and scalability
                -> advanced features <- replication, partitioning, built-in query optimiser, full-text search
                -> management tools
                -> administrative tools
                    -> phpMyAdmin
        -> PostgreSQL
            -> this is an OPEN-SOURCE OBJECT-RELATIONAL DATABASE MANAGEMENT SYSTEM <- ORDBMS
            -> it is reliable, scalable and has a robust feature set
                -> for managing large amounts of data
                -> used for data warehousing, web applications and other data-intensive tasks
            -> this was developed at UC Berkeley
            -> data integrity
            -> concurrency control
            -> SQL support
            -> supports advanced datatypes (arrays)
                -> good for application development
            -> PostgreSQL is good for
                -> data security
                -> support for data encryption
                -> role-based access control
                -> other security features
                -> location-based applications
                    -> built-in support for full-text search and geographic data
            -> avaliable on multiple operating systems
            -> why use PostgreSQL
                -> extensibility <- you can define your own data types, operators and functions
                -> stored procefures can be called without having to retype code
                -> provides triggers and views for complex data manupulation and querying
        -> Oracle
            -> about
                -> an open-source relational database
                -> used by corporate businesses and enterprise customers
                -> IT IS USED FOR ANALYSING GLOBAL DATA USAGE
                    -> it is built on multi-model architecture
                -> it can support relational and NoSQL data
                -> it uses SQL <- STRUCTURED QUERY LANGUAGE for data manipulation
            -> benefits
                -> reliability, scalability and performance
                -> for integrity, transactions, and locking
                -> built-in query optimiser that can auomatically optimise queries, for better performance
                -> security features <- data encryption, role-based access control and auditing
                -> built-in support for high avaliability and desaster recovery
                    -> Data Guard, Real Application Clusters (RAC) and Active Data Guard
                    -> it contains most of the features of other RDBMS's, and more
                    -> ideal for global enterprise businesses
                    -> Oracle Autonomous Database
                        -> fully autonomous, self-driving, self-securing and a self-repairing database service
        -> Microsoft SQL Server
            -> about
                -> a CLOSED-SOURCE relational database
                -> it mimics MySQL
                -> for Microsoft customers only
                    -> it is compatible with Windows and Linux
                -> MS has invested in new features and improvements
                    -> Azure SQL <- cloud database service and SQL database as a service, and SQL on Linux environments
                    -> they released new versions of SQL Server, like SQL Server 2019
                        -> this includes new features and improvements
                            -> support for big data scenarios
                            -> enhanced security and compliance
                            -> improved analytics and AI
            -> benefits
                -> wide use of data types and integrity
                -> advanced features, such as data replication, partitioning, built-in query optimiser, and full-text search
                -> security features
                    -> data encryption
                    -> role-based access control
                    -> auditing
                -> scalability
                -> avaliablity
                -> management and administration tools
        -> MongoDB
            -> about
                -> this is a document-oriented, open source database management system
                -> to store large amounts of dats
                -> part of the NoSQL database family
                    -> FOR UNSTRUCTURED AND SEMI-STRUCTURED DATA
                -> IT STORES DATA IN THE FORM OF BSON (BINARY JSON) DOCUMENTS
                    -> these are like JSON objects
                        -> they can contain several types of data
                            -> strings
                            -> numbers
                            -> arrays
                            -> other documents
                -> ALL OF THESE ARE SYSTEMS FOR MANAGING DATABASES - MONGODB IS ONE
                -> IT'S A DATABASE
            -> benefits
                -> more flexible than traditional relational databases
                -> SHARDING <- IT SCALES HORIZONTALLY ACROSS MULTIPLE SERVERS
                    -> large datasets can be stored and queried efficiently
                        -> across multiple servers
                        -> sometimes, we have too much data for one server
                -> automatic failover and replication
                    -> high avaliability and data durability
                -> a wide variety of indexing options
                    -> full-text search
                    -> geospatial indexing
                    -> query language
                    -> easy to perform complex queries and data analysis
                -> it has an aggregation framework
                    -> this can perform data processing and analytics on large datasets
                -> flexible, scalable
                -> can be used with different applications and use cases
                -> CAN HANDLE UNSTRUCTURED AND SEMI-STRUCTURED DATA
                -> support for horizontal scaling
                -> many query and indexing options
                -> powerful / flexible / scalable
                -> for web and mobile applications, real-time analytics and other big data use cases
                -> ease of use
                    -> developer-friendly features
                        -> works with SQL, C, C++, Java and .NET (multiple languages)
                        -> has a wide range of developer tools and resources
        -> IBM DB2
            -> about
                -> this is a RDBMS <- RELATIONAL DATABASE MANAGEMENT SYSTEM
                -> for enterprise-level data management and processing
                -> made by IBM
                    -> designed to work with other IBM products
                        -> WebSphere
                        -> UBM Congos
                        -> for database management and analysis
                -> for various operating systems <- Windows, Linux and UNIX
                -> large datasets
                    -> advanced data compression and partitioning
                        -> this can reduce storage space required and improve performance
                -> supports a range of data types
                    -> structured
                    -> semi-structured
                    -> unstructured
                    -> built-in support for XML, JSON and RDF data types
                        -> works with diverse datasets
                -> supports advanced data analytics and reporting capabilities
                    -> built-in data mining
                    -> data warehousing tools
                        -> so extracting insights from large data sets is easier
                ->   





"""