""" What_is_a_Database? Webpage Notes
    -> outline
        -> introduction
        -> what is a database?
        -> what can you do with a database?
        -> uses for databases
        -> databases vs spreadsheets
        -> database components
        -> different types of databases
        -> the most popular databases list
            -> MySQL
            -> PostgreSQL
            -> Oracle
            -> Microsoft SQL Server
            -> MongoDB
            -> IBM DB2
            -> Redis
            -> Apache Cassandra
        -> summary: what is a database
    -> introduction
        -> DATABASES ARE FOR THE CONTENTS OF WEBPAGES
            -> they contain values
            -> applications rely on databases to store and manage the data
        -> this lesson is about
            -> the definition of a database
            -> common uses for databases
            -> types of databases
            -> the most popular databases <- MongoDB is part of this
    -> definition of a database
        -> a system for organising structured information (data)
            -> rows / columns, like a spreadsheet
            -> this can be done electronically
                -> we can search / store / analyse and modify data, using a computer system
    -> what you can do with a database
        -> managing data <- large amounts of data in a structured system
        -> accurately store data, for it's integrity
        -> safely store data long-term
            -> data only stored by the application could be lost if it shuts down
            -> third-party storage
        -> ACCESSING DATA CONCURRENTLY <- MULTIPLE USERS CAN ACCESS THE SAME DATA
            -> we can manage multiple users and have the data be consistent
        -> retrieving data <- finding data quickly and efficiently
        -> connecting data <- we can connect different pieces of related data together
    -> uses for databases
        -> different industries use databases
        -> online platforms for storing and managing user information
        -> managing customer and sales data
        -> research organisation analysing large amounts of scientific data
        -> government agencies storing millions of records
        -> retail company managing and understanding inventory data
        -> healthcare organisations storing patient information and medical records
    -> databases vs spreadsheets
        -> DATABASES ARE NOT THE SAME AS SPREADSHEETS
        -> database tables are rows and columns
        -> DATABASES ARE MORE POWERFUL AND USEFUL THAN SPREADSHEETS
            -> DATABASES CAN BE QUERIED, SPREADSHEETS CAN'T IN THE SAME CAPACITY
        -> DATA PERSISTENCE <- SAVING DATA TO A DATABASE IN SOFTWARE ENGINEERING
            -> DATA SAVED BY A JAVASCRIPT APPLICATION CAN BE ACCESSED USING A PYTHON ONE
            -> 
"""